server:
  port: 8010
spring:
  application:
    name: nuochong-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    configService:
      path: /config/**
      serviceId: NUOCHONG-CONFIG-SERVER
    userService:
      path: /user/**
      serviceId: USER-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"


